-- NON-EXECUTABLE TEMPLATE ONLY.
-- Manually replace every bracketed identifier after security and database-owner review.
-- Passwords are intentionally absent; bind credentials through an approved external mechanism.
-- Do not execute this file automatically or against an unknown database.

CREATE ROLE "<MIGRATION_ROLE_IDENTIFIER>" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE "<APPLICATION_ROLE_IDENTIFIER>" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE "<READ_ONLY_ROLE_IDENTIFIER>" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT CONNECT ON DATABASE "<TARGET_DATABASE_IDENTIFIER>" TO "<MIGRATION_ROLE_IDENTIFIER>";
GRANT CONNECT ON DATABASE "<TARGET_DATABASE_IDENTIFIER>" TO "<APPLICATION_ROLE_IDENTIFIER>";
GRANT CONNECT ON DATABASE "<TARGET_DATABASE_IDENTIFIER>" TO "<READ_ONLY_ROLE_IDENTIFIER>";

GRANT USAGE, CREATE ON SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>" TO "<MIGRATION_ROLE_IDENTIFIER>";
GRANT USAGE ON SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>" TO "<APPLICATION_ROLE_IDENTIFIER>";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>" TO "<APPLICATION_ROLE_IDENTIFIER>";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>" TO "<APPLICATION_ROLE_IDENTIFIER>";
GRANT USAGE ON SCHEMA "<APPROVED_ANALYTICS_SCHEMA_IDENTIFIER>" TO "<READ_ONLY_ROLE_IDENTIFIER>";
GRANT SELECT ON ALL TABLES IN SCHEMA "<APPROVED_ANALYTICS_SCHEMA_IDENTIFIER>" TO "<READ_ONLY_ROLE_IDENTIFIER>";

ALTER DEFAULT PRIVILEGES FOR ROLE "<MIGRATION_ROLE_IDENTIFIER>" IN SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>"
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "<APPLICATION_ROLE_IDENTIFIER>";
ALTER DEFAULT PRIVILEGES FOR ROLE "<MIGRATION_ROLE_IDENTIFIER>" IN SCHEMA "<APPLICATION_SCHEMA_IDENTIFIER>"
  GRANT USAGE, SELECT ON SEQUENCES TO "<APPLICATION_ROLE_IDENTIFIER>";

