const VISIT_LIBYA_CONTENT = {
  videos: [
    {
      id: "-KW6pQcq-LI",
      title: "Visit Libya cinematic gateway",
      titleAr: "البوابة السينمائية لزيارة ليبيا",
      description: "A visual invitation to discover Libya through heritage, desert, coast, and authentic experiences.",
      descriptionAr: "دعوة بصرية لاكتشاف ليبيا عبر التراث والصحراء والساحل والتجارب الأصيلة.",
      url: "https://youtu.be/-KW6pQcq-LI"
    },
    {
      id: "XFS_h8s8www",
      title: "Libya, land of civilizations",
      titleAr: "ليبيا أرض الحضارات",
      description: "A tourism film that supports the Visit Libya identity and destination storytelling.",
      descriptionAr: "فيلم سياحي يدعم هوية Visit Libya وسرد الوجهات السياحية.",
      url: "https://youtu.be/XFS_h8s8www"
    },
    {
      id: "YZnbQtQRLgo",
      title: "Authentic experiences in Libya",
      titleAr: "تجارب أصيلة في ليبيا",
      description: "A video for promoting authentic routes, culture, and visitor inspiration.",
      descriptionAr: "فيديو للترويج للمسارات الأصيلة والثقافة وإلهام الزائر.",
      url: "https://youtu.be/YZnbQtQRLgo"
    },
    {
      id: "SF6Ou54SFdo",
      title: "Explore Libya stories",
      titleAr: "حكايات لاكتشاف ليبيا",
      description: "A supporting video for digital campaigns and visual storytelling.",
      descriptionAr: "فيديو داعم للحملات الرقمية والسرد البصري للوجهة.",
      url: "https://youtu.be/SF6Ou54SFdo"
    }
  ],
  gallery: [
    { image: "imges/desert.jpg", title: "Sahara Dunes", titleAr: "كثبان الصحراء", category: "Desert", categoryAr: "الصحراء" },
    { image: "imges/Leptis Magna3.jpeg", title: "Leptis Magna", titleAr: "لبدة الكبرى", category: "World Heritage", categoryAr: "تراث عالمي" },
    { image: "imges/Sabratha.jpg", title: "Sabratha", titleAr: "صبراتة", category: "Coastal Heritage", categoryAr: "تراث ساحلي" },
    { image: "imges/Ghadames2.JPG", title: "Ghadames", titleAr: "غدامس", category: "Oasis City", categoryAr: "مدينة واحة" },
    { image: "imges/Acacus.jpg", title: "Akakus", titleAr: "أكاكوس", category: "Rock Art", categoryAr: "الفن الصخري" },
    { image: "imges/traditional clothing.jpg", title: "Traditional Dress", titleAr: "اللباس التقليدي", category: "Culture", categoryAr: "الثقافة" },
    { image: "imges/Bazin.jpg", title: "Libyan Cuisine", titleAr: "المطبخ الليبي", category: "Food", categoryAr: "المطبخ" },
    { image: "imges/oldtripoli.jpg", title: "Old Tripoli", titleAr: "طرابلس القديمة", category: "Old Cities", categoryAr: "المدن القديمة" }
  ]
};

const VISIT_LIBYA_I18N = {
  ar: {
    "Discover Authenticity": "اكتشف الأصالة",
    "Destinations": "الوجهات",
    "Experiences": "التجارب",
    "Discover": "اكتشف",
    "Culture": "الثقافة",
    "Food": "المطبخ",
    "Folklore": "الفلكلور",
    "Crafts": "الحرف",
    "World Heritage": "التراث العالمي",
    "Videos": "الفيديوهات",
    "Plan Your Trip": "خطط رحلتك",
    "Interactive Map": "الخريطة التفاعلية",
    "عربي": "English",
    "Discover the Timeless\nBeauty of Libya": "اكتشف جمال ليبيا\nالخالد",
    "From ancient Roman ruins to pristine Sahara dunes, experience authenticity like never before": "من المدن الرومانية القديمة إلى كثبان الصحراء النقية، عِش تجربة الأصالة كما لم تعرفها من قبل",
    "Explore Libya": "استكشف ليبيا",
    "Authentic journeys": "رحلات أصيلة",
    "Where civilizations, desert, sea, and living heritage meet": "حيث تلتقي الحضارات والصحراء والبحر والموروث الحي",
    "Visit Libya brings together world heritage, old cities, traditional culture, desert adventures, Mediterranean coastlines, and interactive tourism discovery.": "تجمع Visit Libya بين التراث العالمي والمدن القديمة والثقافة التقليدية ومغامرات الصحراء والسواحل المتوسطية والاكتشاف السياحي التفاعلي.",
    "Adventure": "مغامرة",
    "Sahara & Rock Art": "الصحراء والفن الصخري",
    "Living Libyan Identity": "الهوية الليبية الحية",
    "Ancient Mediterranean Cities": "مدن متوسطية عريقة",
    "Visit Libya Films": "أفلام Visit Libya",
    "Official video stories from Libya": "حكايات مرئية رسمية من ليبيا",
    "Selected YouTube films are connected from one GitHub data file, so the media library can be updated without redesigning the page.": "تم ربط أفلام يوتيوب المختارة من ملف بيانات واحد على GitHub، حتى يمكن تحديث مكتبة الوسائط دون إعادة تصميم الصفحة.",
    "Photo Library": "مكتبة الصور",
    "Real Libyan images linked from GitHub": "صور ليبية حقيقية مرتبطة من GitHub",
    "Browse destinations →": "تصفح الوجهات ←",
    "Featured destinations": "وجهات مختارة",
    "Explore Libya by place": "استكشف ليبيا حسب المكان",
    "View all destinations →": "عرض كل الوجهات ←",
    "Leptis Magna": "لبدة الكبرى",
    "Sabratha": "صبراتة",
    "Ghadames": "غدامس",
    "Akakus": "أكاكوس",
    "World Heritage": "التراث العالمي",
    "Coastal heritage": "تراث ساحلي",
    "Desert oasis": "واحة صحراوية",
    "Rock art": "فن صخري",
    "One of the most remarkable Roman cities on the Libyan Mediterranean coast.": "واحدة من أبرز المدن الرومانية على الساحل الليبي المتوسطي.",
    "A Roman theatre and ancient coastal setting that connects history with the sea.": "مسرح روماني ومشهد ساحلي أثري يربط التاريخ بالبحر.",
    "A historic oasis city of shaded lanes, white architecture, and desert memory.": "مدينة واحة تاريخية بشوارع مظللة وعمارة بيضاء وذاكرة صحراوية.",
    "Desert landscapes and prehistoric rock art preserving humanity's early story.": "مشاهد صحراوية وفن صخري ما قبل التاريخ يحفظ بدايات حكاية الإنسان.",
    "Discover culture": "اكتشف الثقافة",
    "Experience living heritage": "عِش الموروث الحي",
    "Culture in Libya is not a side section. It is the visitor’s pathway to hospitality, traditional dress, crafts, food, markets, folklore, and local stories.": "الثقافة في ليبيا ليست قسمًا جانبيًا، بل طريق الزائر إلى الضيافة واللباس التقليدي والحرف والمطبخ والأسواق والفلكلور والحكايات المحلية.",
    "Explore Culture": "استكشف الثقافة",
    "Navigate Libya through trusted tourism layers": "تنقّل في ليبيا عبر طبقات سياحية موثوقة",
    "Open the national tourism atlas to explore heritage, nature, routes, old cities, accommodation, and visitor services.": "افتح الأطلس السياحي الوطني لاستكشاف التراث والطبيعة والمسارات والمدن القديمة والإيواء وخدمات الزوار.",
    "Open Interactive Map →": "افتح الخريطة التفاعلية ←",
    "Official national tourism platform for presenting Libya through destinations, experiences, culture, routes, and trusted visual storytelling.": "المنصة الوطنية الرسمية لتقديم ليبيا عبر الوجهات والتجارب والثقافة والمسارات والسرد البصري الموثوق.",
    "Explore": "استكشف",
    "Official Attribution": "الصفة الرسمية",
    "Official names appear in the footer only.": "تظهر أسماء الجهات الرسمية في الفوتر فقط.",
    "Choose your Libya": "اختر ليبيا التي تريدها",
    "Destinations that define the country’s tourism identity": "وجهات ترسم هوية ليبيا السياحية",
    "Filter heritage cities, Sahara landscapes, coastal places, nature, and cultural routes with a clean visual experience.": "صفِّ المدن التراثية والمشاهد الصحراوية والوجهات الساحلية والطبيعة والمسارات الثقافية ضمن تجربة بصرية نظيفة.",
    "All": "الكل",
    "Heritage": "التراث",
    "Desert": "الصحراء",
    "Coast": "الساحل",
    "Nature": "الطبيعة",
    "Old Cities": "المدن القديمة",
    "Tripoli": "طرابلس",
    "Cyrene / Shahhat": "قورينا / شحات",
    "Jabal Akhdar": "الجبل الأخضر",
    "Roman city": "مدينة رومانية",
    "Ancient city on the Mediterranean coast.": "مدينة أثرية على الساحل المتوسطي.",
    "Roman theatre and coastal ruins.": "مسرح روماني وآثار ساحلية.",
    "Covered lanes and oasis architecture.": "أزقة مغطاة وعمارة واحاتية.",
    "Rock art and Sahara landscapes.": "فن صخري ومشاهد صحراوية.",
    "Old medina, markets, arch, and coastal identity.": "مدينة قديمة وأسواق وقوس وهوية ساحلية.",
    "Mountain, forests, coast, and classical heritage.": "جبل وغابات وساحل وتراث كلاسيكي.",
    "Travel through experiences": "سافر عبر التجارب",
    "From Sahara adventure to cultural immersion": "من مغامرة الصحراء إلى الانغماس الثقافي",
    "Each card represents a tourism product that can later be expanded into routes, packages, and media campaigns.": "تمثل كل بطاقة منتجًا سياحيًا يمكن تطويره لاحقًا إلى مسارات وبرامج وحملات إعلامية.",
    "Sahara Adventure": "مغامرة الصحراء",
    "Roman Heritage": "التراث الروماني",
    "Coastal Escape": "رحلة الساحل",
    "Cultural Immersion": "الانغماس الثقافي",
    "Green Mountain Nature": "طبيعة الجبل الأخضر",
    "Food & Markets": "المطبخ والأسواق",
    "Camel routes, desert camps, rock art, and dunes.": "مسارات الجمال والمخيمات الصحراوية والفن الصخري والكثبان.",
    "Leptis Magna, Sabratha, Cyrene, and Mediterranean history.": "لبدة الكبرى وصبراتة وقورينا وتاريخ المتوسط.",
    "Beaches, sea routes, old ports, and Mediterranean light.": "شواطئ ومسارات بحرية وموانئ قديمة وضوء متوسطي.",
    "Traditional dress, crafts, food, folklore, and old markets.": "لباس تقليدي وحرف ومطبخ وفلكلور وأسواق قديمة.",
    "Forests, valleys, coastlines, and classical sites.": "غابات وأودية وسواحل ومواقع كلاسيكية.",
    "Taste Libya through cuisine, tea, spices, and souks.": "تذوق ليبيا عبر المطبخ والشاي والتوابل والأسواق.",
    "Discover Libya’s living identity": "اكتشف الهوية الليبية الحية",
    "Culture, food, folklore, crafts, and world heritage": "الثقافة والمطبخ والفلكلور والحرف والتراث العالمي",
    "The Discover section gathers Libya’s living identity in one visual, elegant gateway.": "يجمع قسم اكتشف الهوية الليبية الحية في بوابة بصرية أنيقة واحدة.",
    "Living Libyan culture": "الثقافة الليبية الحية",
    "Hospitality, old markets, traditional dress, local stories, and the visual language of Libya’s communities.": "الضيافة والأسواق القديمة واللباس التقليدي والحكايات المحلية واللغة البصرية للمجتمعات الليبية.",
    "Libyan cuisine": "المطبخ الليبي",
    "Music, performance & horse traditions": "الموسيقى وفنون الأداء وتقاليد الفروسية",
    "Handmade identity": "هوية مصنوعة باليد",
    "Civilizations in place": "حضارات حاضرة في المكان",
    "Old cities and souks": "المدن القديمة والأسواق",
    "Food as a journey": "المطبخ كرحلة",
    "Bazin, couscous, asida, tea, spices, and family hospitality present a deeper way to experience Libya.": "البازين والكسكسي والعصيدة والشاي والتوابل والضيافة العائلية تقدم طريقًا أعمق لتجربة ليبيا.",
    "Folklore and performance": "الفلكلور وفنون الأداء",
    "Music, horse traditions, ceremonies, and social celebrations help visitors understand the living memory of communities.": "الموسيقى وتقاليد الفروسية والطقوس والاحتفالات الاجتماعية تساعد الزائر على فهم الذاكرة الحية للمجتمعات.",
    "Traditional crafts": "الصناعات التقليدية",
    "Pottery, palm crafts, weaving, leather, copper, silver, and handmade objects connect tourism with local value chains.": "الفخار والسعفيات والنسيج والجلود والنحاس والفضة والمنتجات اليدوية تربط السياحة بسلاسل القيمة المحلية.",
    "World heritage as the foundation": "التراث العالمي أساس الهوية",
    "Leptis Magna, Sabratha, Cyrene, Ghadames, and Akakus give Libya a globally recognized tourism identity.": "لبدة الكبرى وصبراتة وقورينا وغدامس وأكاكوس تمنح ليبيا هوية سياحية معترفًا بها عالميًا.",
    "Libya’s world heritage places": "مواقع ليبيا للتراث العالمي",
    "Outstanding heritage sites that connect Mediterranean history, desert urbanism, classical civilizations, and ancient rock art.": "مواقع تراثية استثنائية تربط تاريخ المتوسط والعمران الصحراوي والحضارات الكلاسيكية والفن الصخري القديم.",
    "Plan a refined journey across Libya": "خطط لرحلة راقية عبر ليبيا",
    "Practical, elegant planning information to help visitors understand routes, seasons, preparation, and responsible travel.": "معلومات عملية وأنيقة تساعد الزائر على فهم المسارات والمواسم والاستعداد والسفر المسؤول.",
    "Choose your theme": "اختر نمط رحلتك",
    "Pick your route": "اختر مسارك",
    "Prepare responsibly": "استعد بمسؤولية",
    "Best seasons": "أفضل المواسم",
    "Desert readiness": "الاستعداد للصحراء",
    "Build your trip": "ابنِ رحلتك",
    "Begin with a 7-day civilizations route": "ابدأ بمسار الحضارات لمدة 7 أيام",
    "Tripoli, Sabratha, Leptis Magna, Old Tripoli, museums, markets, and cultural dining.": "طرابلس وصبراتة ولبدة الكبرى وطرابلس القديمة والمتاحف والأسواق وتجربة الطعام الثقافي.",
    "Explore route →": "استكشف المسار ←",
    "Explore Libya through a clean tourism map": "استكشف ليبيا عبر خريطة سياحية نظيفة",
    "The map interface must use accurate Libya boundaries only. No manual or distorted borders should be used.": "يجب أن تستخدم واجهة الخريطة حدود ليبيا الدقيقة فقط، ولا يجوز استخدام حدود مرسومة يدويًا أو مشوهة.",
    "Tourism layers": "الطبقات السياحية",
    "Filters for trusted discovery": "فلاتر لاكتشاف موثوق",
    "Use verified map assets and tourism layers for heritage, nature, desert, coast, accommodation, food, and routes.": "استخدم أصول خرائط موثقة وطبقات سياحية للتراث والطبيعة والصحراء والساحل والإيواء والمطاعم والمسارات.",
    "Open National Atlas →": "افتح الأطلس الوطني ←",
    "Ask before you explore": "اسأل قبل أن تستكشف",
    "A guided interface that will later connect visitors to destinations, routes, culture, atlas layers, and travel planning.": "واجهة إرشادية ستربط الزائر لاحقًا بالوجهات والمسارات والثقافة وطبقات الأطلس وتخطيط الرحلة.",
    "Demo Assistant": "مساعد تجريبي",
    "What would you like to discover?": "ماذا تريد أن تكتشف؟",
    "Ask about Sahara Adventure, Roman Heritage, Culture, Food, Folklore, Crafts, or the Interactive Map.": "اسأل عن مغامرة الصحراء أو التراث الروماني أو الثقافة أو الطعام أو الفلكلور أو الحرف أو الخريطة التفاعلية.",
    "Ask about Libya...": "اسأل عن ليبيا...",
    "Ask": "اسأل"
  }
};
