import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const arg=n=>{const i=process.argv.indexOf(n);return i<0?undefined:process.argv[i+1]};
export function origin(value){let u;try{u=new URL(value)}catch{throw new Error("SITE_ORIGIN must be an absolute HTTPS origin")}if(u.protocol!=="https:"||u.username||u.password||u.pathname!=="/"||u.search||u.hash)throw new Error("SITE_ORIGIN must be a credential-free HTTPS origin without a path");return u.origin}
export function base(value){const v=String(value||"/");if(!v.startsWith("/")||v.includes("\\")||v.split("/").includes(".."))throw new Error("Invalid SITE_BASE_PATH");return `${v.replace(/\/+$/,'')}/`}
const xml=v=>v.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function render({siteOrigin,basePath,manifest}){const o=origin(siteOrigin),b=base(basePath),url=p=>`${o}${b}${p==='index.html'?'':p}`;const entries=manifest.pagePairs.filter(x=>x.indexable&&x.sitemap!==false).flatMap(x=>[[x.page,x.page,`ar/${x.page}`],[`ar/${x.page}`,x.page,`ar/${x.page}`]]);return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${entries.map(([p,en,ar])=>`  <url>\n    <loc>${xml(url(p))}</loc>\n    <xhtml:link rel="alternate" hreflang="en" href="${xml(url(en))}" />\n    <xhtml:link rel="alternate" hreflang="ar" href="${xml(url(ar))}" />\n    <xhtml:link rel="alternate" hreflang="x-default" href="${xml(url(en))}" />\n  </url>`).join('\n')}\n</urlset>\n`}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const manifest=JSON.parse(fs.readFileSync(path.resolve(arg('--manifest')||path.join(root,'config/frontend-pages.json')),'utf8'));const value=arg('--site-origin')||process.env.SITE_ORIGIN;if(!value)throw new Error('SITE_ORIGIN or --site-origin is required');const out=path.resolve(arg('--output')||path.join(root,'sitemap.xml'));fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,render({siteOrigin:value,basePath:arg('--base-path')||manifest.projectBasePath,manifest}));console.log(`Generated ${out}`)}catch(e){console.error(`Sitemap generation failed: ${e.message}`);process.exitCode=1}}
